@startuml
skinparam defaultFontName Roboto
skinparam defaultFontSize 20

package "nl.openweb.command-handler.core.clj" #White{
    component "cmt-handler" as mth #Yellow
    component "cac-handler" as ach #Yellow
    component consumer as c #Yellow
    component producer as p #Yellow
}
package balancedb #White{
    database balance #LightBlue
    database cac #LightBlue
    database cmt #LightBlue
}
component Kafka as kc #F26724

mth --> cmt :check/update\nstatus
ach --> cac :check/update\nstatus
mth --> balance :check/update\nbalance
ach --> balance :creates\nbalance
p --> kc :AccountCreationConfirmed,\nAccountCreationFailed,\nMoneyTransferConfirmed,\nMoneyTransferFailed and\nBalanceChanged\n(three different topics)
c <-- kc :ConfirmAccountCreation\n and ConfirmMoneyTransfer

@enduml