@startuml
skinparam defaultFontName Montserrat
skinparam defaultFontSize 20

package "nl.openweb.command-handler.core.clj" #White{
    component consumer as c #Yellow
    component producer as p #Yellow
    component "cmt-handler" as mth #Yellow
    component "cac-handler" as ach #Yellow
}
package balancedb #LightBlue{
    database balance #EFEFF3
    database cac #EFEFF3
    database cmt #EFEFF3
}
component Kafka as kc #F26724

mth --> cmt :check/update status
ach --> cac :check/update status
mth --> balance :check/update balance
ach --> balance :crates balance
kc <--- p :AccountCreationConfirmed,\nAccountCreationFailed,\nMoneyTransferConfirmed,\nMoneyTransferFailed and\nBalanceChanged
c <--- kc :ConfirmAccountCreation\n and ConfirmMoneyTransfer

@enduml