@startuml
skinparam defaultFontName Roboto
skinparam defaultFontSize 20

component producer as p #Yellow
component consumer as c #Yellow
component kafka as kc #LightGrey
actor client as cl
component "schema-provider" as sp #Yellow

sp <-right-> cl :request transfer\lusing server
sp --> p :executes function\nresulting in a\n transfer and\ncreates subscription\nfor the result
c -right-> sp :send MoneyTransferResult\nfor active subscriptions
p --> kc :produces\lConfirmMoneyTransfer
c <-- kc :consumes\lMoneyTransferConfirmed\nand\nMoneyTransferFailed

@enduml