@startuml
skinparam shadowing false
skinparam defaultFontName Roboto
skinparam defaultFontSize 26

component producer as p #Yellow
component consumer as c #Yellow
component kafka as kc #LightGrey
actor client as cl #White
component "schema-provider" as sp #Yellow

cl <-right-> sp :request transfer\lusing server
sp --> p :executes function\nresulting in a\n transfer and\ncreates subscription\nfor the result
p --> kc :produces\lConfirmMoneyTransfer
c <-- kc :consumes\lMoneyTransferConfirmed\nand\nMoneyTransferFailed
sp <-- c :send MoneyTransferResult\nfor active subscriptions

@enduml