@startuml
skinparam shadowing false
skinparam defaultFontName Roboto
skinparam defaultFontSize 26

actor client as cl #White
entity "GraphQL endpoint" as ge #Yellow
database transactiondb as pgt #LightBlue
boundary "Kafka" as ka #LightGrey

cl -> ge : Subscribe to get_account stream
ge -> pgt : Create account with uuid
ge -> ka : Send an account creation command
activate ge
ka -> ge : Sends records about account creation
ge -> ge : Filter on uuid
ge -> cl : Send account creation result
cl -> cl : Store bank account and token
cl -> ge : End subscription with id
deactivate ge

@enduml