@startuml
skinparam defaultFontName Roboto
skinparam defaultFontSize 20

actor client as cl #White
entity "GraphQL endpoint" as ge #Yellow
database transactiondb as pgt #LightBlue
entity "Kafka" as ka #LightGrey

cl -> ge : Subscribe to get_account stream
ge -> pgt : Create account with uuid
ge -> ka : Create a ConfirmAccountCreation
ka -> ka : Process
ge -> ka : Polling records
ka -> ge : Sends records one being an AccountCreationConfirmed
ge -> ge : Filter on uuid
ge -> cl : Send AccountResult
cl -> cl : Store iban and token
cl -> ge : End subscription get_account

@enduml