@startuml
skinparam shadowing false
skinparam defaultFontName Roboto
skinparam defaultFontSize 26

package nl.openweb.test #Yellow {
    component file.clj as fi
    component analysis.clj as an
}
file "{category}.edn" as map
file "test-runs" as tr
file "{category}.json" as ht

fi <-- map :reads the file
fi <-- tr: reads the mapped files
an --> ht: combine the data to\la format vega can use.

@enduml
