@startuml
skinparam shadowing false
skinparam defaultFontName Roboto
skinparam defaultFontSize 26

database balancedb as pgb #LightBlue
database transactiondb as pgt #LightBlue
[Kafka] as ka #LightGrey
[Command handler] as ch #Yellow
[GraphQL endpoint] as ge #Yellow
[Frontend server] as fs #LightGreen
actor client as cl #White

pgb <-> ch : keep track which\rmessages have been handled\nkeep the balances
pgt <-> ge : stores/queries transactions\rstores profiles
fs -> cl : provides frontend code
cl <--> ge : exchange information\nusing GraphQL
ch <-up-> ka : exchange data using avro
ge <--> ka : exchange data using avro


@enduml