@startuml
skinparam shadowing false
skinparam defaultFontName Roboto
skinparam defaultFontSize 26

database balancedb as pgb #LightBlue
database transactiondb as pgt #LightBlue
[Kafka] as ka #LightGrey
[Command handler] as ch #Yellow
[GraphQL endpoint] as ge #Yellow
[Frontend server] as fs #LightGreen
actor client as cl #White

cl <- fs
cl <---> ge
ch <-up-> ka
ge <--> ka
ch <-right-> pgb : executes commands
ge <-right-> pgt : derived state
@enduml