@startuml
skinparam sequence ActorBorderColor #A61D48
skinparam component {
  BorderColor #A61D48
  ArrowColor #A61D48
  FontSize 22
  ArrowFontSize 10
}
skinparam database {
  BorderColor #A61D48
  FontSize 20
}

left to right direction

[Kafka cluster] as kc #F26724
[Zookeeper cluster] as zc #F26724
[Schema registry] as sr #F26724
[Synchronizer] as sy #D4D4D4
[Heartbeat] as hb #D4D4D4
[Command generator] as cg #D4D4D4
[Command handler] as ch #D4D4D4
[GraphQL endpoint] as ge #D4D4D4
[Frontend server] as fs #31BEC2
actor client as cl #EFEFF3
database balancedb as pgb #ABC8E7
database transactiondb as pgt #ABC8E7

sy ..> sr : set schemas
sy ..> kc : creates topics
fs --> cl : provides frontend code
cl <--> ge : exchange information\nusing GraphQL
kc <..> zc : get and set meta data
cg <--> kc : exchange data using avro
kc <--> ch : exchange data using avro
kc <--> ge : exchange data using avro
hb --> kc : produces Heartbeat
pgb <-> ch : keep track witch\rmessages have been handled\nkeep the balances
pgt <-> ge : stores/queries transactions\rstores profiles
sr --> ch : get schemas
sr --> ge : get schemas
sr -> kc : store schemas
hb <-- sr : get schemas
cg <-- sr : get schemas

@enduml