@startuml
skinparam shadowing false
skinparam defaultFontName Roboto
skinparam defaultFontSize 26

package nl.openweb.test #White {
    component load.clj as lo #Yellow
    component file.clj as fi #Yellow
    component interactions.clj as in #Yellow
    component generator.clj as ge #Yellow
    component process.clj as pr #Yellow
}
component "Chrome driver" as cd #Pink
["<color:white>Docker</color>"] as do #DarkBlue
file output

ge <- lo: adds generator every minute
pr -right-> do :get cpu and\lmemory of\ncontainers
ge --> do :does transactions\ldirectly on endpoint\lmax 4 per second
lo --> fi: provides latencies of\lgenerators
fi -> pr: run every 20 iterations
in -right-> fi: time latency
fi --> output :writes the data
in <-up-> cd :logs in and\lmakes a transaction\levery second

@enduml