@startuml
skinparam shadowing false
skinparam defaultFontName Roboto
skinparam defaultFontSize 26

actor client as cl #White
database transaction as tr #LightBlue
component consumer as c #Yellow
component kafka as kc #LightGrey
component "schema-provider" as sp #Yellow

cl <-> sp :queries or subscribe\lto transactions
sp -> tr :sql query on\lderived state
tr <-- c :insert transactions
c <-- kc :consumes\nBalanceChanged
c --> sp :send transaction\nfor active subscriptions


@enduml