@startuml
skinparam defaultFontName Roboto
skinparam defaultFontSize 20

database transaction as tr #LightBlue
component consumer as c #Yellow
actor client as cl #White
component kafka as kc #LightGrey

component "schema-provider" as sp #Yellow

tr <- c :insert transactions
c <- kc :consumes\nBalanceChanged
sp <-> cl :queries or subscribe\lto transactions
tr <-- sp :sql query on\lderived state
c --> sp :send transaction\nfor active subscriptions


@enduml