@startuml
skinparam shadowing false
skinparam defaultFontName Roboto
skinparam defaultFontSize 26
hide footbox

actor client as cl #White
entity "GraphQL endpoint" as ge #Yellow
boundary "Kafka" as ka #LightGrey

cl -> cl : Fill in amount, to, and description
cl -> ge : Subscribe to money_transfer stream
ge -> ka : Send a transfer money command
activate ge
ka -> ge : Sends records about money transfers
ge -> ge : Filter on uuid
ge -> cl : Send money transfer result
cl -> ge : End subscription with id
deactivate ge

@enduml